# frontend/components/language_manager.py
import streamlit as st

TEXTS = {
    "English": {
        # Navigation
        "nav_employee_db": "Employee Database",
        "nav_recruitment": "Recruitment Pipeline",
        "nav_dashboard": "HR Dashboard",
        "nav_resume_screener": "Resume Screener",
        
        # Landing Page
        "app_title": "AI HR Management System",
        "app_subtitle": "Intelligent Recruitment | Employee Management | HR Analytics",
        "key_features": "Key Features",
        "feature_ai_resume": "AI Resume Screener",
        "feature_ai_resume_desc": "Smart resume analysis with Gemini AI",
        "feature_employee_db": "Employee Database",
        "feature_employee_db_desc": "Centralized employee records management",
        "feature_recruitment": "Recruitment Pipeline",
        "feature_recruitment_desc": "Kanban-style candidate tracking",
        "feature_hr_analytics": "HR Analytics",
        "feature_hr_analytics_desc": "Real-time dashboard and insights",
        "quick_actions": "Quick Actions",
        "screen_resumes": "Screen Resumes",
        "manage_employees": "Manage Employees",
        "view_dashboard": "View Dashboard",
        
        # Language selector
        "select_language": "SELECT LANGUAGE",
        "lang_english": "English",
        "lang_thai": "Thai",
        "lang_chinese": "Chinese",
        "launch": "Launch",
        "footer_text": "AI-Powered HR Management System | Version 2.0",
        "footer_powered_by": "Powered by Google Gemini AI | Intelligent Resume Screening | HR Analytics",
        
        # Employee Database
        "emp_title": "Employee Database",
        "emp_subtitle": "Manage employee records efficiently",
        "emp_list": "Employee List",
        "emp_add": "Add Employee",
        "emp_stats": "Statistics",
        "emp_search": "Search Employee",
        "emp_search_placeholder": "Search by name, code, or department...",
        "emp_total": "Total Employees",
        "emp_active": "Active",
        "emp_departments": "Departments",
        "emp_avg_salary": "Avg Salary",
        "emp_avg_score": "Average Score",
        "emp_no_data": "No employee data available",
        "emp_code": "Employee Code",
        "emp_first_name": "First Name",
        "emp_last_name": "Last Name",
        "emp_thai_name": "Thai Name",
        "emp_department": "Department",
        "emp_position": "Position",
        "emp_level": "Level",
        "emp_hire_date": "Hire Date",
        "emp_birth_date": "Birth Date",
        "emp_email": "Email",
        "emp_phone": "Phone",
        "emp_address": "Address",
        "emp_salary": "Salary (THB)",
        "emp_bank": "Bank",
        "emp_bank_account": "Bank Account Number",
        "emp_status": "Status",
        "emp_actions": "Actions",
        "emp_add_success": "Employee added successfully!",
        "emp_update_success": "Employee updated successfully!",
        "emp_delete_success": "Employee deleted successfully!",
        "emp_confirm_delete": "Are you sure you want to delete this employee?",
        "emp_select_department": "Select Department",
        "emp_select_position": "Select Position",
        "emp_select_level": "Select Level",
        "emp_select_bank": "Select Bank",
        "view_details": "View Details",
        
        # Department options
        "dept_engineering": "Engineering",
        "dept_marketing": "Marketing",
        "dept_sales": "Sales",
        "dept_hr": "Human Resources",
        "dept_finance": "Finance",
        "dept_operations": "Operations",
        
        # Position options
        "pos_manager": "Manager",
        "pos_senior": "Senior",
        "pos_junior": "Junior",
        "pos_intern": "Intern",
        "pos_director": "Director",
        "pos_specialist": "Specialist",
        
        # Level options
        "level_entry": "Entry Level",
        "level_mid": "Mid Level",
        "level_senior": "Senior Level",
        "level_lead": "Lead",
        "level_executive": "Executive",
        
        # Bank options
        "bank_bangkok": "Bangkok Bank",
        "bank_krungsri": "Krungsri Bank",
        "bank_kasikorn": "Kasikorn Bank",
        "bank_scb": "SCB Bank",
        "bank_krungthai": "Krungthai Bank",
        "bank_tmb": "TMB Bank",
        
        # Recruitment Pipeline
        "rec_title": "Recruitment Pipeline",
        "rec_subtitle": "Track candidates through hiring pipeline",
        "rec_new": "New",
        "rec_screening": "Screening",
        "rec_interview": "Interview",
        "rec_offer": "Offer",
        "rec_hired": "Hired",
        "rec_rejected": "Rejected",
        "rec_add_candidate": "Add New Candidate",
        "rec_upcoming": "Upcoming Interviews",
        "rec_candidate_name": "Name",
        "rec_candidate_email": "Email",
        "rec_candidate_phone": "Phone",
        "rec_position": "Position Applied",
        "rec_score": "AI Score",
        "rec_no_candidates": "No candidates in this stage",
        "rec_no_upcoming": "No upcoming interviews scheduled",
        "rec_add_title": "Add New Candidate",
        "rec_name_placeholder": "Enter full name",
        "rec_email_placeholder": "Enter email address",
        "rec_phone_placeholder": "Enter phone number",
        "rec_select_position": "Select Position",
        "rec_resume_upload": "Upload Resume (PDF)",
        "rec_notes": "Additional Notes",
        "rec_notes_placeholder": "Enter any additional information...",
        "rec_submit": "Submit Candidate",
        "rec_cancel": "Cancel",
        "rec_move_to": "Move to",
        "rec_schedule_interview": "Schedule Interview",
        "rec_interview_date": "Date",
        "rec_interview_time": "Time",
        "rec_interview_location": "Location/Virtual Link",
        "rec_add_note": "Add Note",
        "rec_candidate_details": "Candidate Details",
        "candidates_lower": "candidates",
        
        # HR Dashboard
        "dashboard_title": "HR Dashboard",
        "dashboard_subtitle": "Real-time HR analytics and insights",
        "dashboard_total_employees": "Total Employees",
        "dashboard_turnover": "Turnover Rate",
        "dashboard_open_positions": "Open Positions",
        "dashboard_upcoming": "Upcoming Interviews",
        "dashboard_by_dept": "Employees by Department",
        "dashboard_pipeline": "Candidate Pipeline",
        "dashboard_recent_hires": "Recent Hires",
        "dashboard_alerts": "Alerts",
        "dashboard_no_dept_data": "No department data",
        "dashboard_no_candidate_data": "No candidate data",
        "dashboard_no_recent_hires": "No recent hires",
        "dashboard_probation_alert": "{name} - Probation ends soon",
        "dashboard_no_alerts": "No pending probation endings",
        "dashboard_turnover_calc": "Turnover Rate Calculation",
        "dashboard_avg_tenure": "Average Tenure (Years)",
        "dashboard_gender_ratio": "Gender Ratio",
        "dashboard_age_distribution": "Age Distribution",
        "dashboard_salary_distribution": "Salary Distribution",
        "dashboard_hiring_trends": "Hiring Trends",
        
        # Resume Screener
        "resume_title": "AI Resume Screener",
        "resume_subtitle": "Intelligent resume screening powered by Google Gemini AI",
        "resume_jd": "Job Description",
        "resume_jd_placeholder": "Paste the job description here...",
        "resume_jd_example": "Example: We are looking for a Software Engineer with 3+ years of experience in Python...",
        "resume_jd_required": "Please enter job description",
        "resume_files_required": "Please upload resumes",
        "resume_upload": "Upload Resumes",
        "resume_upload_label": "Choose PDF files",
        "resume_upload_help": "Supported format: PDF",
        "resume_start": "Start Analysis",
        "resume_clear": "Clear All",
        "resume_results": "Results",
        "resume_ranking": "Ranking Overview",
        "resume_details": "Candidate Details",
        "resume_uploading": "Uploading files to server...",
        "resume_analyzing": "AI is analyzing resumes...",
        "resume_complete": "Analysis complete!",
        "resume_no_results": "No results yet. Upload resumes and click Start Analysis",
        "resume_error_connection": "Cannot connect to backend server",
        "resume_error_timeout": "Request timed out. Please try again",
        "resume_score": "Match Score",
        "resume_rank": "Rank",
        "resume_strengths": "Strengths",
        "resume_weaknesses": "Areas for Improvement",
        "resume_recommendation": "Recommendation",
        "resume_download_report": "Download Full Report",
        "resume_reset": "Reset",
        "files_selected": "file(s) selected",
        "statistics": "Statistics",
        "score_distribution": "Score Distribution",
        "top_skills": "Top Skills",
        
        # Sidebar specific
        "job_description": "Job Description",
        "paste_jd": "Paste your job description here:",
        "jd_placeholder": "Example: We're looking for a Senior Python Developer with experience in AI/ML...",
        "upload_resumes": "Upload Resumes",
        "drag_drop": "Drag and drop files here",
        "file_limit": "Limit 200MB per file • PDF",
        "browse_files": "Browse files",
        "language_settings": "Language Settings",
        "select_language": "Select Language",
        "start_screening": "Start Screening",
        "processing": "Processing...",
        "current_results": "Current Results",
        "please_upload": "Please upload resumes and click 'Start Screening' to begin.",
        "how_it_works": "How it works",
        "step1": "1. **Upload Job Description** - Paste your job requirements in the sidebar",
        "step2": "2. **Upload Resumes** - Upload PDF files of candidate resumes",
        "step3": "3. **Start Screening** - Click the button to begin AI analysis",
        "step4": "4. **Review Results** - See ranked candidates with detailed analysis",
        "evaluation_criteria": "The AI evaluates candidates based on:",
        "criteria1": "- **Technical Skills (40%)**",
        "criteria2": "- **Experience (30%)**",
        "criteria3": "- **Education/Projects (20%)**",
        "criteria4": "- **Soft Skills (10%)**",
        "missing_jd": "Please enter a job description",
        "missing_files": "Please upload at least one resume",
        "analyzing": "Analyzing resumes...",
        "history": "History",
        "employees": "Employees",
        "list": "List",
        "add_form": "Add Form",
        "stats": "Stats",
        
        # Common UI Elements
        "search": "Search...",
        "add": "Add",
        "edit": "Edit",
        "delete": "Delete",
        "cancel": "Cancel",
        "save": "Save",
        "update": "Update",
        "confirm": "Confirm",
        "loading": "Loading...",
        "error": "Error",
        "success": "Success",
        "warning": "Warning",
        "info": "Information",
        "language": "Language",
        "filter_by": "Filter by",
        "status": "Status",
        "all": "All",
        "active": "Active",
        "resigned": "Resigned",
        "back_to_home": "Back to Home",
        "no_data": "No data available",
        "yes": "Yes",
        "no": "No",
        "ok": "OK",
        "close": "Close",
        "refresh": "Refresh",
        "export": "Export",
        "import": "Import",
        "download": "Download",
        "upload": "Upload",
        "view": "View",
        "more_info": "More Info",
        "required_field": "This field is required",
        "invalid_email": "Please enter a valid email address",
        "invalid_phone": "Please enter a valid phone number",
        
        # Pipeline status messages
        "status_new": "New",
        "status_screening": "Screening", 
        "status_interview": "Interview",
        "status_offer": "Offer",
        "status_hired": "Hired",
        "status_rejected": "Rejected",
        
        # Month names
        "january": "January",
        "february": "February",
        "march": "March",
        "april": "April",
        "may": "May",
        "june": "June",
        "july": "July",
        "august": "August",
        "september": "September",
        "october": "October",
        "november": "November",
        "december": "December",
        
        # Chart labels
        "chart_employees": "Number of Employees",
        "chart_salary": "Salary (THB)",
        "chart_age": "Age",
        "chart_count": "Count",
        "chart_percentage": "Percentage",
        
        # UI Parts Metrics
        "total_candidates": "Total Candidates",
        "average_score": "Average Score",
        "top_score": "Top Score",
        "passing_rate": "Passing Rate",
        
        # UI Parts Loading
        "analyzing_subtitle": "Using advanced AI algorithms",
        
        # UI Parts Badges
        "badge_exceptional": "Exceptional",
        "badge_strong_match": "Strong Match",
        "badge_good_match": "Good Match",
        "badge_needs_review": "Needs Review",
        
        # UI Parts Skills
        "matched_skills": "Matched Skills",
        "missing_skills": "Missing Skills",
        "none_found": "None found",
    },
    
    "Thai": {
        # Navigation
        "nav_employee_db": "ฐานข้อมูลพนักงาน",
        "nav_recruitment": "ระบบสรรหาบุคลากร",
        "nav_dashboard": "แดชบอร์ดทรัพยากรบุคคล",
        "nav_resume_screener": "โปรแกรมสแกนเรซูเม่",
        
        # Landing Page
        "app_title": "ระบบบริหารทรัพยากรบุคคลด้วยเอไอ",
        "app_subtitle": "สรรหาอัจฉริยะ | จัดการพนักงาน | วิเคราะห์ทรัพยากรบุคคล",
        "key_features": "คุณสมบัติหลัก",
        "feature_ai_resume": "โปรแกรมสแกนเรซูเม่ด้วยเอไอ",
        "feature_ai_resume_desc": "วิเคราะห์เรซูเม่อัจฉริยะด้วย Gemini AI",
        "feature_employee_db": "ฐานข้อมูลพนักงาน",
        "feature_employee_db_desc": "จัดการบันทึกพนักงานแบบรวมศูนย์",
        "feature_recruitment": "ระบบสรรหาบุคลากร",
        "feature_recruitment_desc": "ติดตามผู้สมัครแบบคัมบัง",
        "feature_hr_analytics": "การวิเคราะห์ทรัพยากรบุคคล",
        "feature_hr_analytics_desc": "แดชบอร์ดและข้อมูลเชิงลึกแบบเรียลไทม์",
        "quick_actions": "การดำเนินการด่วน",
        "screen_resumes": "สแกนเรซูเม่",
        "manage_employees": "จัดการพนักงาน",
        "view_dashboard": "ดูแดชบอร์ด",
        
        # Language selector
        "select_language": "เลือกภาษา",
        "lang_english": "อังกฤษ",
        "lang_thai": "ไทย",
        "lang_chinese": "จีน",
        "launch": "เปิดใช้งาน",
        "footer_text": "ระบบบริหารทรัพยากรบุคคลด้วยเอไอ | เวอร์ชัน 2.0",
        "footer_powered_by": "ขับเคลื่อนโดย Google Gemini AI | การคัดกรองเรซูเม่อัจฉริยะ | การวิเคราะห์ทรัพยากรบุคคล",
        
        # Employee Database
        "emp_title": "ฐานข้อมูลพนักงาน",
        "emp_subtitle": "จัดการบันทึกพนักงานอย่างมีประสิทธิภาพ",
        "emp_list": "รายชื่อพนักงาน",
        "emp_add": "เพิ่มพนักงาน",
        "emp_stats": "สถิติ",
        "emp_search": "ค้นหาพนักงาน",
        "emp_search_placeholder": "ค้นหาด้วยชื่อ รหัส หรือแผนก...",
        "emp_total": "พนักงานทั้งหมด",
        "emp_active": "กำลังทำงาน",
        "emp_departments": "แผนก",
        "emp_avg_salary": "เงินเดือนเฉลี่ย",
        "emp_avg_score": "คะแนนเฉลี่ย",
        "emp_no_data": "ไม่มีข้อมูลพนักงาน",
        "emp_code": "รหัสพนักงาน",
        "emp_first_name": "ชื่อ",
        "emp_last_name": "นามสกุล",
        "emp_thai_name": "ชื่อภาษาไทย",
        "emp_department": "แผนก",
        "emp_position": "ตำแหน่ง",
        "emp_level": "ระดับ",
        "emp_hire_date": "วันที่เริ่มงาน",
        "emp_birth_date": "วันเกิด",
        "emp_email": "อีเมล",
        "emp_phone": "เบอร์โทรศัพท์",
        "emp_address": "ที่อยู่",
        "emp_salary": "เงินเดือน (บาท)",
        "emp_bank": "ธนาคาร",
        "emp_bank_account": "เลขที่บัญชีธนาคาร",
        "emp_status": "สถานะ",
        "emp_actions": "การดำเนินการ",
        "emp_add_success": "เพิ่มพนักงานเรียบร้อยแล้ว!",
        "emp_update_success": "อัพเดทพนักงานเรียบร้อยแล้ว!",
        "emp_delete_success": "ลบพนักงานเรียบร้อยแล้ว!",
        "emp_confirm_delete": "คุณแน่ใจหรือไม่ที่จะลบพนักงานนี้?",
        "emp_select_department": "เลือกแผนก",
        "emp_select_position": "เลือกตำแหน่ง",
        "emp_select_level": "เลือกระดับ",
        "emp_select_bank": "เลือกธนาคาร",
        "view_details": "ดูรายละเอียด",
        
        # Department options
        "dept_engineering": "วิศวกรรม",
        "dept_marketing": "การตลาด",
        "dept_sales": "ขาย",
        "dept_hr": "ทรัพยากรบุคคล",
        "dept_finance": "การเงิน",
        "dept_operations": "ปฏิบัติการ",
        
        # Position options
        "pos_manager": "ผู้จัดการ",
        "pos_senior": "อาวุโส",
        "pos_junior": "จูเนียร์",
        "pos_intern": "ฝึกงาน",
        "pos_director": "ผู้อำนวยการ",
        "pos_specialist": "ผู้เชี่ยวชาญ",
        
        # Level options
        "level_entry": "ระดับเริ่มต้น",
        "level_mid": "ระดับกลาง",
        "level_senior": "ระดับอาวุโส",
        "level_lead": "หัวหน้าทีม",
        "level_executive": "ผู้บริหาร",
        
        # Bank options
        "bank_bangkok": "ธนาคารกรุงเทพ",
        "bank_krungsri": "ธนาคารกรุงศรี",
        "bank_kasikorn": "ธนาคารกสิกรไทย",
        "bank_scb": "ธนาคารไทยพาณิชย์",
        "bank_krungthai": "ธนาคารกรุงไทย",
        "bank_tmb": "ธนาคารทหารไทย",
        
        # Recruitment Pipeline
        "rec_title": "ระบบสรรหาบุคลากร",
        "rec_subtitle": "ติดตามผู้สมัครผ่านระบบสรรหาบุคลากร",
        "rec_new": "ใหม่",
        "rec_screening": "กำลังตรวจสอบ",
        "rec_interview": "สัมภาษณ์",
        "rec_offer": "เสนอข้อเสนอ",
        "rec_hired": "รับงานแล้ว",
        "rec_rejected": "ไม่ผ่าน",
        "rec_add_candidate": "เพิ่มผู้สมัครใหม่",
        "rec_upcoming": "การสัมภาษณ์ที่จะถึง",
        "rec_candidate_name": "ชื่อ",
        "rec_candidate_email": "อีเมล",
        "rec_candidate_phone": "เบอร์โทรศัพท์",
        "rec_position": "ตำแหน่งที่สมัคร",
        "rec_score": "คะแนนเอไอ",
        "rec_no_candidates": "ไม่มีผู้สมัครในขั้นตอนนี้",
        "rec_no_upcoming": "ไม่มีการนัดสัมภาษณ์ที่กำลังจะถึง",
        "rec_add_title": "เพิ่มผู้สมัครใหม่",
        "rec_name_placeholder": "ป้อนชื่อเต็ม",
        "rec_email_placeholder": "ป้อนที่อยู่อีเมล",
        "rec_phone_placeholder": "ป้อนเบอร์โทรศัพท์",
        "rec_select_position": "เลือกตำแหน่ง",
        "rec_resume_upload": "อัปโหลดเรซูเม่ (PDF)",
        "rec_notes": "หมายเหตุเพิ่มเติม",
        "rec_notes_placeholder": "ป้อนข้อมูลเพิ่มเติม...",
        "rec_submit": "ส่งผู้สมัคร",
        "rec_cancel": "ยกเลิก",
        "rec_move_to": "ย้ายไป",
        "rec_schedule_interview": "นัดสัมภาษณ์",
        "rec_interview_date": "วันที่สัมภาษณ์",
        "rec_interview_time": "เวลาสัมภาษณ์",
        "rec_interview_location": "สถานที่/ลิงค์ประชุมออนไลน์",
        "rec_add_note": "เพิ่มหมายเหตุ",
        "rec_candidate_details": "รายละเอียดผู้สมัคร",
        "candidates_lower": "ผู้สมัคร",
        
        # HR Dashboard
        "dashboard_title": "แดชบอร์ดทรัพยากรบุคคล",
        "dashboard_subtitle": "การวิเคราะห์และข้อมูลเชิงลึกทรัพยากรบุคคลแบบเรียลไทม์",
        "dashboard_total_employees": "พนักงานทั้งหมด",
        "dashboard_turnover": "อัตราการออกจากงาน",
        "dashboard_open_positions": "ตำแหน่งว่าง",
        "dashboard_upcoming": "การสัมภาษณ์ที่จะถึง",
        "dashboard_by_dept": "พนักงานแยกตามแผนก",
        "dashboard_pipeline": "สถานะผู้สมัคร",
        "dashboard_recent_hires": "พนักงานใหม่ล่าสุด",
        "dashboard_alerts": "การแจ้งเตือน",
        "dashboard_no_dept_data": "ไม่มีข้อมูลแผนก",
        "dashboard_no_candidate_data": "ไม่มีข้อมูลผู้สมัคร",
        "dashboard_no_recent_hires": "ไม่มีพนักงานใหม่ล่าสุด",
        "dashboard_probation_alert": "{name} - กำลังจะหมดระยะทดลองงาน",
        "dashboard_no_alerts": "ไม่มีการแจ้งเตือน",
        "dashboard_turnover_calc": "การคำนวณอัตราการออกจากงาน",
        "dashboard_avg_tenure": "อายุงานเฉลี่ย (ปี)",
        "dashboard_gender_ratio": "อัตราส่วนเพศ",
        "dashboard_age_distribution": "การกระจายตัวของอายุ",
        "dashboard_salary_distribution": "การกระจายตัวของเงินเดือน",
        "dashboard_hiring_trends": "แนวโน้มการจ้างงาน",
        
        # Resume Screener
        "resume_title": "โปรแกรมสแกนเรซูเม่ด้วยเอไอ",
        "resume_subtitle": "การคัดกรองเรซูเม่อัจฉริยะด้วย Google Gemini AI",
        "resume_jd": "รายละเอียดงาน",
        "resume_jd_placeholder": "วางรายละเอียดงานที่นี่...",
        "resume_jd_example": "ตัวอย่าง: เรากำลังมองหาวิศวกรซอฟต์แวร์ที่มีประสบการณ์ 3+ ปีใน Python...",
        "resume_jd_required": "กรุณาระบุรายละเอียดงาน",
        "resume_files_required": "กรุณาอัปโหลดเรซูเม่",
        "resume_upload": "อัปโหลดเรซูเม่",
        "resume_upload_label": "เลือกไฟล์ PDF",
        "resume_upload_help": "รูปแบบที่รองรับ: PDF",
        "resume_start": "เริ่มการวิเคราะห์",
        "resume_clear": "ล้างทั้งหมด",
        "resume_results": "ผลลัพธ์",
        "resume_ranking": "ภาพรวมการจัดอันดับ",
        "resume_details": "รายละเอียดผู้สมัคร",
        "resume_uploading": "กำลังอัปโหลดไฟล์ไปยังเซิร์ฟเวอร์...",
        "resume_analyzing": "เอไอกำลังวิเคราะห์เรซูเม่...",
        "resume_complete": "การวิเคราะห์เสร็จสมบูรณ์!",
        "resume_no_results": "ยังไม่มีผลลัพธ์ อัปโหลดเรซูเม่และคลิกเริ่มการวิเคราะห์",
        "resume_error_connection": "ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์แบ็คเอนด์ได้",
        "resume_error_timeout": "คำขอหมดเวลา กรุณาลองอีกครั้ง",
        "resume_score": "คะแนนความเหมาะสม",
        "resume_rank": "อันดับ",
        "resume_strengths": "จุดแข็ง",
        "resume_weaknesses": "จุดที่ต้องปรับปรุง",
        "resume_recommendation": "คำแนะนำ",
        "resume_download_report": "ดาวน์โหลดรายงานฉบับสมบูรณ์",
        "resume_reset": "รีเซ็ต",
        "files_selected": "ไฟล์",
        "statistics": "สถิติ",
        "score_distribution": "การกระจายของคะแนน",
        "top_skills": "ทักษะยอดนิยม",
        
        # Sidebar specific
        "job_description": "รายละเอียดงาน",
        "paste_jd": "วางรายละเอียดงานของคุณที่นี่:",
        "jd_placeholder": "ตัวอย่าง: เรากำลังมองหา Senior Python Developer ที่มีประสบการณ์ด้าน AI/ML...",
        "upload_resumes": "อัปโหลดเรซูเม่",
        "drag_drop": "ลากและวางไฟล์ที่นี่",
        "file_limit": "จำกัด 200MB ต่อไฟล์ • PDF",
        "browse_files": "เลือกไฟล์",
        "language_settings": "ตั้งค่าภาษา",
        "select_language": "เลือกภาษา",
        "start_screening": "เริ่มวิเคราะห์",
        "processing": "กำลังประมวลผล...",
        "current_results": "ผลลัพธ์ปัจจุบัน",
        "please_upload": "กรุณาอัปโหลดเรซูเม่และคลิก 'เริ่มวิเคราะห์' เพื่อเริ่มต้น",
        "how_it_works": "วิธีการทำงาน",
        "step1": "1. **อัปโหลดรายละเอียดงาน** - วางข้อกำหนดงานในแถบด้านข้าง",
        "step2": "2. **อัปโหลดเรซูเม่** - อัปโหลดไฟล์ PDF ของเรซูเม่ผู้สมัคร",
        "step3": "3. **เริ่มวิเคราะห์** - คลิกปุ่มเพื่อเริ่มการวิเคราะห์ด้วย AI",
        "step4": "4. **ตรวจสอบผลลัพธ์** - ดูอันดับผู้สมัครพร้อมการวิเคราะห์โดยละเอียด",
        "evaluation_criteria": "เกณฑ์การประเมินของ AI:",
        "criteria1": "- **ทักษะทางเทคนิค (40%)**",
        "criteria2": "- **ประสบการณ์ (30%)**",
        "criteria3": "- **การศึกษา/โปรเจค (20%)**",
        "criteria4": "- **ทักษะอ่อน (10%)**",
        "missing_jd": "กรุณาใส่รายละเอียดงาน",
        "missing_files": "กรุณาอัปโหลดเรซูเม่อย่างน้อย 1 ไฟล์",
        "analyzing": "กำลังวิเคราะห์เรซูเม่...",
        "history": "ประวัติ",
        "employees": "พนักงาน",
        "list": "รายชื่อ",
        "add_form": "เพิ่มข้อมูล",
        "stats": "สถิติ",
        
        # Common UI Elements
        "search": "ค้นหา...",
        "add": "เพิ่ม",
        "edit": "แก้ไข",
        "delete": "ลบ",
        "cancel": "ยกเลิก",
        "save": "บันทึก",
        "update": "อัพเดท",
        "confirm": "ยืนยัน",
        "loading": "กำลังโหลด...",
        "error": "ข้อผิดพลาด",
        "success": "สำเร็จ",
        "warning": "คำเตือน",
        "info": "ข้อมูล",
        "language": "ภาษา",
        "filter_by": "กรองตาม",
        "status": "สถานะ",
        "all": "ทั้งหมด",
        "active": "กำลังทำงาน",
        "resigned": "ลาออกแล้ว",
        "back_to_home": "กลับหน้าแรก",
        "no_data": "ไม่มีข้อมูล",
        "yes": "ใช่",
        "no": "ไม่",
        "ok": "ตกลง",
        "close": "ปิด",
        "refresh": "รีเฟรช",
        "export": "ส่งออก",
        "import": "นำเข้า",
        "download": "ดาวน์โหลด",
        "upload": "อัปโหลด",
        "view": "ดู",
        "more_info": "ข้อมูลเพิ่มเติม",
        "required_field": "จำเป็นต้องกรอกข้อมูลนี้",
        "invalid_email": "กรุณาป้อนที่อยู่อีเมลที่ถูกต้อง",
        "invalid_phone": "กรุณาป้อนเบอร์โทรศัพท์ที่ถูกต้อง",
        
        # Pipeline status messages
        "status_new": "ใหม่",
        "status_screening": "กำลังตรวจสอบ",
        "status_interview": "สัมภาษณ์",
        "status_offer": "เสนอข้อเสนอ",
        "status_hired": "รับงานแล้ว",
        "status_rejected": "ไม่ผ่าน",
        
        # Month names
        "january": "มกราคม",
        "february": "กุมภาพันธ์",
        "march": "มีนาคม",
        "april": "เมษายน",
        "may": "พฤษภาคม",
        "june": "มิถุนายน",
        "july": "กรกฎาคม",
        "august": "สิงหาคม",
        "september": "กันยายน",
        "october": "ตุลาคม",
        "november": "พฤศจิกายน",
        "december": "ธันวาคม",
        
        # Chart labels
        "chart_employees": "จำนวนพนักงาน",
        "chart_salary": "เงินเดือน (บาท)",
        "chart_age": "อายุ",
        "chart_count": "จำนวน",
        "chart_percentage": "เปอร์เซ็นต์",
        
        # UI Parts Metrics
        "total_candidates": "ผู้สมัครทั้งหมด",
        "average_score": "คะแนนเฉลี่ย",
        "top_score": "คะแนนสูงสุด",
        "passing_rate": "อัตราผ่านเกณฑ์",
        
        # UI Parts Loading
        "analyzing_subtitle": "ใช้เทคโนโลยี AI ขั้นสูง",
        
        # UI Parts Badges
        "badge_exceptional": "ยอดเยี่ยม",
        "badge_strong_match": "ตรงกับตำแหน่งมาก",
        "badge_good_match": "ตรงกับตำแหน่งดี",
        "badge_needs_review": "ต้องพิจารณาเพิ่ม",
        
        # UI Parts Skills
        "matched_skills": "ทักษะที่ตรงกับงาน",
        "missing_skills": "ทักษะที่ขาด",
        "none_found": "ไม่พบข้อมูล",
    },
    
    "Chinese": {
        # Navigation
        "nav_employee_db": "员工数据库",
        "nav_recruitment": "招聘流程",
        "nav_dashboard": "人力资源仪表板",
        "nav_resume_screener": "简历筛选器",
        
        # Landing Page
        "app_title": "人工智能人力资源管理系统",
        "app_subtitle": "智能招聘 | 员工管理 | 人力资源分析",
        "key_features": "主要功能",
        "feature_ai_resume": "人工智能简历筛选",
        "feature_ai_resume_desc": "使用Gemini AI进行智能简历分析",
        "feature_employee_db": "员工数据库",
        "feature_employee_db_desc": "集中式员工记录管理",
        "feature_recruitment": "招聘流程",
        "feature_recruitment_desc": "看板式候选人跟踪",
        "feature_hr_analytics": "人力资源分析",
        "feature_hr_analytics_desc": "实时仪表板和洞察",
        "quick_actions": "快速操作",
        "screen_resumes": "筛选简历",
        "manage_employees": "管理员工",
        "view_dashboard": "查看仪表板",
        
        # Language selector
        "select_language": "选择语言",
        "lang_english": "英语",
        "lang_thai": "泰语",
        "lang_chinese": "中文",
        "launch": "启动",
        "footer_text": "人工智能驱动的人力资源管理系统 | 版本 2.0",
        "footer_powered_by": "由Google Gemini AI驱动 | 智能简历筛选 | 人力资源分析",
        
        # Employee Database
        "emp_title": "员工数据库",
        "emp_subtitle": "高效管理员工记录",
        "emp_list": "员工列表",
        "emp_add": "添加员工",
        "emp_stats": "统计",
        "emp_search": "搜索员工",
        "emp_search_placeholder": "按姓名、工号或部门搜索...",
        "emp_total": "员工总数",
        "emp_active": "在职",
        "emp_departments": "部门",
        "emp_avg_salary": "平均工资",
        "emp_avg_score": "平均分",
        "emp_no_data": "没有员工数据",
        "emp_code": "员工编号",
        "emp_first_name": "名",
        "emp_last_name": "姓",
        "emp_thai_name": "泰文名",
        "emp_department": "部门",
        "emp_position": "职位",
        "emp_level": "级别",
        "emp_hire_date": "入职日期",
        "emp_birth_date": "出生日期",
        "emp_email": "电子邮箱",
        "emp_phone": "电话号码",
        "emp_address": "地址",
        "emp_salary": "工资（泰铢）",
        "emp_bank": "银行",
        "emp_bank_account": "银行账号",
        "emp_status": "状态",
        "emp_actions": "操作",
        "emp_add_success": "员工添加成功！",
        "emp_update_success": "员工更新成功！",
        "emp_delete_success": "员工删除成功！",
        "emp_confirm_delete": "您确定要删除这名员工吗？",
        "emp_select_department": "选择部门",
        "emp_select_position": "选择职位",
        "emp_select_level": "选择级别",
        "emp_select_bank": "选择银行",
        "view_details": "查看详情",
        
        # Department options
        "dept_engineering": "工程部",
        "dept_marketing": "市场部",
        "dept_sales": "销售部",
        "dept_hr": "人力资源部",
        "dept_finance": "财务部",
        "dept_operations": "运营部",
        
        # Position options
        "pos_manager": "经理",
        "pos_senior": "高级",
        "pos_junior": "初级",
        "pos_intern": "实习生",
        "pos_director": "总监",
        "pos_specialist": "专员",
        
        # Level options
        "level_entry": "入门级",
        "level_mid": "中级",
        "level_senior": "高级",
        "level_lead": "领导",
        "level_executive": "高管",
        
        # Bank options
        "bank_bangkok": "曼谷银行",
        "bank_krungsri": "大城银行",
        "bank_kasikorn": "开泰银行",
        "bank_scb": "汇商银行",
        "bank_krungthai": "泰京银行",
        "bank_tmb": "军人银行",
        
        # Recruitment Pipeline
        "rec_title": "招聘流程",
        "rec_subtitle": "通过招聘流程跟踪候选人",
        "rec_new": "新候选人",
        "rec_screening": "筛选中",
        "rec_interview": "面试",
        "rec_offer": "录用通知",
        "rec_hired": "已录用",
        "rec_rejected": "已拒绝",
        "rec_add_candidate": "添加新候选人",
        "rec_upcoming": "即将到来的面试",
        "rec_candidate_name": "姓名",
        "rec_candidate_email": "邮箱",
        "rec_candidate_phone": "电话",
        "rec_position": "申请职位",
        "rec_score": "人工智能评分",
        "rec_no_candidates": "此阶段没有候选人",
        "rec_no_upcoming": "没有即将到来的面试",
        "rec_add_title": "添加新候选人",
        "rec_name_placeholder": "输入全名",
        "rec_email_placeholder": "输入邮箱地址",
        "rec_phone_placeholder": "输入电话号码",
        "rec_select_position": "选择职位",
        "rec_resume_upload": "上传简历（PDF）",
        "rec_notes": "附加说明",
        "rec_notes_placeholder": "输入任何附加信息...",
        "rec_submit": "提交候选人",
        "rec_cancel": "取消",
        "rec_move_to": "移动到",
        "rec_schedule_interview": "安排面试",
        "rec_interview_date": "面试日期",
        "rec_interview_time": "面试时间",
        "rec_interview_location": "地点/虚拟链接",
        "rec_add_note": "添加备注",
        "rec_candidate_details": "候选人详情",
        "candidates_lower": "候选人",
        
        # HR Dashboard
        "dashboard_title": "人力资源仪表板",
        "dashboard_subtitle": "实时人力资源分析和洞察",
        "dashboard_total_employees": "员工总数",
        "dashboard_turnover": "离职率",
        "dashboard_open_positions": "空缺职位",
        "dashboard_upcoming": "即将到来的面试",
        "dashboard_by_dept": "按部门统计员工",
        "dashboard_pipeline": "候选人流程",
        "dashboard_recent_hires": "最近录用",
        "dashboard_alerts": "提醒",
        "dashboard_no_dept_data": "没有部门数据",
        "dashboard_no_candidate_data": "没有候选人数据",
        "dashboard_no_recent_hires": "没有最近录用",
        "dashboard_probation_alert": "{name} - 试用期即将结束",
        "dashboard_no_alerts": "没有待处理的试用期结束提醒",
        "dashboard_turnover_calc": "离职率计算",
        "dashboard_avg_tenure": "平均任期（年）",
        "dashboard_gender_ratio": "性别比例",
        "dashboard_age_distribution": "年龄分布",
        "dashboard_salary_distribution": "工资分布",
        "dashboard_hiring_trends": "招聘趋势",
        
        # Resume Screener
        "resume_title": "人工智能简历筛选器",
        "resume_subtitle": "由Google Gemini AI驱动的智能简历筛选",
        "resume_jd": "职位描述",
        "resume_jd_placeholder": "在此粘贴职位描述...",
        "resume_jd_example": "示例：我们正在寻找一名具有3年以上Python经验的软件工程师...",
        "resume_jd_required": "请输入职位描述",
        "resume_files_required": "请上传简历",
        "resume_upload": "上传简历",
        "resume_upload_label": "选择PDF文件",
        "resume_upload_help": "支持的格式：PDF",
        "resume_start": "开始分析",
        "resume_clear": "清除全部",
        "resume_results": "结果",
        "resume_ranking": "排名概览",
        "resume_details": "候选人详情",
        "resume_uploading": "正在上传文件到服务器...",
        "resume_analyzing": "人工智能正在分析简历...",
        "resume_complete": "分析完成！",
        "resume_no_results": "暂无结果。上传简历并点击开始分析",
        "resume_error_connection": "无法连接到后端服务器",
        "resume_error_timeout": "请求超时，请重试",
        "resume_score": "匹配分数",
        "resume_rank": "排名",
        "resume_strengths": "优势",
        "resume_weaknesses": "需要改进的方面",
        "resume_recommendation": "建议",
        "resume_download_report": "下载完整报告",
        "resume_reset": "重置",
        "files_selected": "个文件",
        "statistics": "统计",
        "score_distribution": "分数分布",
        "top_skills": "热门技能",
        
        # Sidebar specific
        "job_description": "职位描述",
        "paste_jd": "在此粘贴您的职位描述：",
        "jd_placeholder": "示例：我们正在寻找一位具有AI/ML经验的高级Python开发人员...",
        "upload_resumes": "上传简历",
        "drag_drop": "将文件拖放到此处",
        "file_limit": "每个文件限制200MB • PDF",
        "browse_files": "浏览文件",
        "language_settings": "语言设置",
        "select_language": "选择语言",
        "start_screening": "开始筛选",
        "processing": "处理中...",
        "current_results": "当前结果",
        "please_upload": "请上传简历并点击'开始筛选'",
        "how_it_works": "使用方法",
        "step1": "1. **上传职位描述** - 在侧边栏粘贴职位要求",
        "step2": "2. **上传简历** - 上传PDF格式的候选人简历",
        "step3": "3. **开始筛选** - 点击按钮开始AI分析",
        "step4": "4. **查看结果** - 查看排名候选人及详细分析",
        "evaluation_criteria": "AI评估候选人的依据：",
        "criteria1": "- **技术技能 (40%)**",
        "criteria2": "- **经验 (30%)**",
        "criteria3": "- **教育/项目 (20%)**",
        "criteria4": "- **软技能 (10%)**",
        "missing_jd": "请输入职位描述",
        "missing_files": "请至少上传一份简历",
        "analyzing": "正在分析简历...",
        "history": "历史",
        "employees": "员工",
        "list": "列表",
        "add_form": "添加表单",
        "stats": "统计",
        
        # Common UI Elements
        "search": "搜索...",
        "add": "添加",
        "edit": "编辑",
        "delete": "删除",
        "cancel": "取消",
        "save": "保存",
        "update": "更新",
        "confirm": "确认",
        "loading": "加载中...",
        "error": "错误",
        "success": "成功",
        "warning": "警告",
        "info": "信息",
        "language": "语言",
        "filter_by": "筛选条件",
        "status": "状态",
        "all": "全部",
        "active": "在职",
        "resigned": "已离职",
        "back_to_home": "返回首页",
        "no_data": "无数据",
        "yes": "是",
        "no": "否",
        "ok": "确定",
        "close": "关闭",
        "refresh": "刷新",
        "export": "导出",
        "import": "导入",
        "download": "下载",
        "upload": "上传",
        "view": "查看",
        "more_info": "更多信息",
        "required_field": "此字段为必填项",
        "invalid_email": "请输入有效的邮箱地址",
        "invalid_phone": "请输入有效的电话号码",
        
        # Pipeline status messages
        "status_new": "新候选人",
        "status_screening": "筛选中",
        "status_interview": "面试中",
        "status_offer": "录用通知",
        "status_hired": "已录用",
        "status_rejected": "已拒绝",
        
        # Month names
        "january": "一月",
        "february": "二月",
        "march": "三月",
        "april": "四月",
        "may": "五月",
        "june": "六月",
        "july": "七月",
        "august": "八月",
        "september": "九月",
        "october": "十月",
        "november": "十一月",
        "december": "十二月",
        
        # Chart labels
        "chart_employees": "员工数量",
        "chart_salary": "工资（泰铢）",
        "chart_age": "年龄",
        "chart_count": "数量",
        "chart_percentage": "百分比",
        
        # UI Parts Metrics
        "total_candidates": "候选人总数",
        "average_score": "平均分",
        "top_score": "最高分",
        "passing_rate": "通过率",
        
        # UI Parts Loading
        "analyzing_subtitle": "使用高级AI算法",
        
        # UI Parts Badges
        "badge_exceptional": "优秀",
        "badge_strong_match": "高度匹配",
        "badge_good_match": "良好匹配",
        "badge_needs_review": "需要审核",
        
        # UI Parts Skills
        "matched_skills": "匹配的技能",
        "missing_skills": "缺失的技能",
        "none_found": "未找到",
    }
}

def get_text(key, default=None):
    """
    Get translated text for current language
    
    Args:
        key (str): The translation key
        default (str, optional): Default value if key not found
    
    Returns:
        str: Translated text or key if not found
    """
    lang = st.session_state.get('language', 'Thai')
    result = TEXTS.get(lang, TEXTS['Thai']).get(key)
    
    if result is None:
        if default is not None:
            return default
        return key
    return result

def init_language():
    """Initialize language in session state"""
    if 'language' not in st.session_state:
        st.session_state['language'] = 'Thai'

def set_language(lang):
    """
    Set language in session state
    
    Args:
        lang (str): Language code ('Thai', 'English', or 'Chinese')
    """
    if lang != st.session_state.get('language'):
        st.session_state['language'] = lang
        st.rerun()

def render_language_selector():
    """Render language selector in sidebar with buttons"""
    st.markdown("---")
    st.markdown(get_text("language_settings"))
    
    current_lang = st.session_state.get('language', 'Thai')
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        if st.button("Thai", key="lang_thai", use_container_width=True):
            if current_lang != "Thai":
                set_language("Thai")
    
    with col2:
        if st.button("English", key="lang_eng", use_container_width=True):
            if current_lang != "English":
                set_language("English")
    
    with col3:
        if st.button("Chinese", key="lang_cn", use_container_width=True):
            if current_lang != "Chinese":
                set_language("Chinese")

def render_simple_language_selector():
    """Simple language selector using radio buttons (alternative)"""
    st.markdown("---")
    st.markdown(get_text("select_language"))
    
    current_lang = st.session_state.get('language', 'Thai')
    
    lang_options = {
        "Thai": "Thai",
        "English": "English",
        "Chinese": "Chinese"
    }
    
    selected_lang = st.radio(
        "",
        options=list(lang_options.keys()),
        format_func=lambda x: lang_options[x],
        index=list(lang_options.keys()).index(current_lang),
        key="lang_selector_simple",
        label_visibility="collapsed",
        horizontal=True
    )
    
    if selected_lang != current_lang:
        set_language(selected_lang)